### ISSUE TITLE
Game fails to open after removing a mod from the mods folder

### ISSUE THREAD

**Issue by Roaxial** [TotallyNotSethP/DnDGMod#11]
SCRIPT ERROR: Invalid get index '276' (on base: 'Dictionary').
          at: get_unread_card_ids (res://singletons/MetaProgression.gdc:115)
SCRIPT ERROR: Invalid call. Nonexistent function 'size' in base 'Nil'.
          at: show_title_cards (res://ChoiceUI.gdc:322)

The script tries to load the collection data of the cards that no longer exist, and this causes an issue that makes the title screen not fully load up
![image](https://github.com/TotallyNotSethP/DnDGMod/assets/117025107/baaced20-1f74-429e-9003-2e4865691ae1)

**Comment by TotallyNotSethP** [comment]
Fixed by wiping save data when compiling
